#include "tmds_encode.h"
#include "pico.h"
#include <stdint.h>

// Expanded palette table: 256 entries × 3 bytes
// Index = color byte (hi nibble = bg, lo nibble = fg)
// Each entry contains packed 6-bit values for the TMDS LUT:
//   { B_packed, G_packed, R_packed }
// where each byte = (bg_3bit << 3) | fg_3bit
// This format matches what the TMDS LUT expects for its upper index bits.
__attribute__((section(".scratch_x.palette_table"), aligned(4)))
uint8_t palette_table[256 * 3];

// Include the pre-generated TMDS lookup table
// Generated by: python3 generate_palettised_1bpp_tables.py 8
#include "tmds_tables.h"

// ============================================================================
// Palette Functions
// ============================================================================

// Map 2-bit blue (0-3) to 3-bit (0-7) with optimal intensity approximation.
// Target intensities: 0, 1/3, 2/3, 1 → 3-bit levels: 0, 2, 5, 7
static const uint8_t blue_2to3[4] = {0, 2, 5, 7};

void set_palette(const uint8_t *fg_palette, const uint8_t *bg_palette) {
    for (int bg = 0; bg < 16; bg++) {
        for (int fg = 0; fg < 16; fg++) {
            uint8_t color_byte = (bg << 4) | fg;
            uint8_t bg_rgb332 = bg_palette[bg];
            uint8_t fg_rgb332 = fg_palette[fg];
            
            // Extract R, G, B values from RGB332 format
            // RGB332: bits 7:5 = R (3-bit), bits 4:2 = G (3-bit), bits 1:0 = B (2-bit)
            uint8_t bg_r3 = (bg_rgb332 >> 5) & 0x07;
            uint8_t bg_g3 = (bg_rgb332 >> 2) & 0x07;
            uint8_t bg_b3 = blue_2to3[bg_rgb332 & 0x03];  // Map 2-bit to 3-bit optimally
            
            uint8_t fg_r3 = (fg_rgb332 >> 5) & 0x07;
            uint8_t fg_g3 = (fg_rgb332 >> 2) & 0x07;
            uint8_t fg_b3 = blue_2to3[fg_rgb332 & 0x03];  // Map 2-bit to 3-bit optimally
            
            // Pack 3-bit values as (bg_3bit << 3) | fg_3bit for each channel.
            // This creates a 6-bit value that indexes into the TMDS LUT.
            // The LUT is organized with bg in bits 5:3 and fg in bits 2:0.
            // PicoDVI TMDS planes are ordered: 0=Blue, 1=Green, 2=Red
            palette_table[color_byte * 3 + 0] = (bg_b3 << 3) | fg_b3;  // B plane (TMDS lane 0)
            palette_table[color_byte * 3 + 1] = (bg_g3 << 3) | fg_g3;  // G plane (TMDS lane 1)
            palette_table[color_byte * 3 + 2] = (bg_r3 << 3) | fg_r3;  // R plane (TMDS lane 2)
        }
    }
}
