configs:
  - name: "Basic 2.0"
    setup:
      - action: "load"
        files:
          - address: 0x8800
            file: "/roms/901439-08.bin"
          - address: 0xc000
            file: "/roms/901439-01.bin"
          - address: 0xd000
            file: "/roms/901439-02.bin"
          - address: 0xe000
            file: "/roms/901439-03.bin"
          - address: 0xf000
            # https://hub.inktada.com/channel/rom1diskmagic
            file: "/roms/rom1diskrom_v15.bin"
            # file: "/roms/901439-04.bin"            
          - address: 0xc800
            file: "/roms/901439-05.bin"
          - address: 0xd800
            file: "/roms/901439-06.bin"
          - address: 0xf800
            file: "/roms/901439-07.bin"
      - if: "graphics"
        then:
          # Use ROM '901439-03' (loaded above)
          - action: "set-usb-keymap"
            file: "/ukm/us-grus.bin"
        else:
          # Commodore never produced an edit ROM for the business keyboard for the original ROM set.
          # This patch replaces the original keyscan routine with one adapted from '901474-01'.
          - action: "patch"
            address: 0x0e702
            hex: "b01148bd5be7d007a9018d0402d0038e230268caf00888d0e6ee10e8d0d7ad2302cd0302f0318d0302aa302bbd5be708297f2830184e04029013c92c900dc93cb009e90fc920b00569202c0980ae0d029d0f02e820ece74c7ee650e73a03393633dfb12fff134d205812b2ffffb02c4e565ab300ffae2e424300b4db4f1155544551145049dc59525789b6c04c0d4a474441b53b4bdd4846539bb9ffdeb7b0373431ffff1db82d383532"
          - action: "patch"
            address: 0x0e7ec
            hex: "e00ad00af0060a6905a00060a2008e0d02d0f800"
          - action: "set-usb-keymap"
            file: "/ukm/us-buuk.bin"
      # Original PET roms polled VIA ($E840) to delay screen updates until vertical blanking
      # to avoid "sparkle" artifacts. On later CRTC models this is unnecessary and causes
      # delays due to short vsync pulses. This copy elides the delay loop.
      - action: "copy"
        source: 0xe7b4
        destination: 0xe7ad
        length: 0x06
  - name: "Basic 4.0 (40 Col 50 Hz)"
    setup:
      - action: "load"
        files:
          - address: 0x8800
            file: "/roms/901447-10.bin"
          - address: 0xb000
            file: "/roms/901465-19.bin"
          - address: 0xc000
            file: "/roms/901465-20.bin"
          - address: 0xd000
            file: "/roms/901465-21.bin"
          - address: 0xe000
            file: "/roms/901498-01.bin"
          - address: 0xf000
            file: "/roms/901465-22.bin"
      - if: "graphics"
        then:
          # Use ROM '901499-01' (loaded above)
          - action: "set-usb-keymap"
            file: "/ukm/us-grus.bin"
        else:
          # Commodore never produced an edit ROM for the business keyboard.
          - action: "patch"
            address: 0xe55c
            hex: "aa08297f28301746989013c92c900dc93cb009e90fc920b00569202c"
          - action: "patch"
            address: 0xe73f
            hex: "16043a03393633dfb12f15134d205812b2100fb02c4e565ab30019ae2e424300b4db4f1155544551145049dc59525709b6c04c0d4a474441b53b4bdd4846539bb906deb7b0373431050e1db82d383532"
          - action: "set-usb-keymap"
            file: "/ukm/us-buuk.bin"
  - name: "Basic 4.0 (40 Col 60 Hz)"
    setup:
      - action: "load"
        files:
          - address: 0x8800
            file: "/roms/901447-10.bin"
          - address: 0xb000
            file: "/roms/901465-19.bin"
          - address: 0xc000
            file: "/roms/901465-20.bin"
          - address: 0xd000
            file: "/roms/901465-21.bin"
          - address: 0xe000
            file: "/roms/901499-01.bin"
          - address: 0xf000
            file: "/roms/901465-22.bin"
      - if: "graphics"
        then:
          # Use ROM '901499-01' (loaded above)
          - action: "set-usb-keymap"
            file: "/ukm/us-grus.bin"          
        else:
          # Commodore never produced an edit ROM for the business keyboard.
          - action: "patch"
            address: 0xe55c
            hex: "aa08297f28301746989013c92c900dc93cb009e90fc920b00569202c"
          - action: "patch"
            address: 0xe73f
            hex: "16043a03393633dfb12f15134d205812b2100fb02c4e565ab30019ae2e424300b4db4f1155544551145049dc59525709b6c04c0d4a474441b53b4bdd4846539bb906deb7b0373431050e1db82d383532"
          - action: "set-usb-keymap"
            file: "/ukm/us-buuk.bin"
  - name: "Basic 4.0 (80 Col 60 Hz)"
    setup:
      - action: "load"
        files:
          - file: "/roms/901447-10.bin"
            address: 0x8800
          - file: "/roms/901465-19.bin"
            address: 0xb000
          - file: "/roms/901465-20.bin"
            address: 0xc000
          - file: "/roms/901465-21.bin"
            address: 0xd000
          - file: "/roms/901474-03.bin"
            address: 0xe000
          - file: "/roms/901465-22.bin"
            address: 0xf000
      - action: "set"
        columns: 80
  - name: "Basic 4.0 (80 Col 50 Hz)"
    setup:
      - action: "load"
        files:
          - file: "/roms/901447-10.bin"
            address: 0x8800
          - file: "/roms/901465-19.bin"
            address: 0xb000
          - file: "/roms/901465-20.bin"
            address: 0xc000
          - file: "/roms/901465-21.bin"
            address: 0xd000
          - file: "/roms/901474-04.bin"
            address: 0xe000
          - file: "/roms/901465-22.bin"
            address: 0xf000
      - action: "set"
        columns: 80
