configs:
  - name: "Basic 2.0"
    setup:
      - action: "load"
        files:
          - file: "/roms/901439-08.bin"
            address: 0x8800
          - file: "/roms/901439-01.bin"
            address: 0xc000
          - file: "/roms/901439-02.bin"
            address: 0xd000
          - file: "/roms/901439-03.bin"
            address: 0xe000
          - file: "/roms/901439-04.bin"
            address: 0xf000
          - file: "/roms/901439-05.bin"
            address: 0xc800
          - file: "/roms/901439-06.bin"
            address: 0xd800
          - file: "/roms/901439-07.bin"
            address: 0xf800
      - action: "copy"
        source: 0xe7b4
        destination: 0xe7ad
        length: 0x06
  - name: "Basic 4.0 (40 Col 50 Hz)"
    setup:
      - action: "load"
        files:
          - file: "/roms/901447-10.bin"
            address: 0x8800
          - file: "/roms/901465-19.bin"
            address: 0xb000
          - file: "/roms/901465-20.bin"
            address: 0xc000
          - file: "/roms/901465-21.bin"
            address: 0xd000
          - file: "/roms/901499-01.bin"
            address: 0xe000
          - file: "/roms/901465-22.bin"
            address: 0xf000
  - name: "Basic 4.0 (40 Col 60 Hz)"
    setup:
      - action: "load"
        files:
          - file: "/roms/901447-10.bin"
            address: 0x8800
          - file: "/roms/901465-19.bin"
            address: 0xb000
          - file: "/roms/901465-20.bin"
            address: 0xc000
          - file: "/roms/901465-21.bin"
            address: 0xd000
          - file: "/roms/901499-01.bin"
            address: 0xe000
          - file: "/roms/901465-22.bin"
            address: 0xf000
  - name: "Basic 4.0 (80 Col 60 Hz)"
    setup:
      - action: "load"
        files:
          - file: "/roms/901447-10.bin"
            address: 0x8800
          - file: "/roms/901465-19.bin"
            address: 0xb000
          - file: "/roms/901465-20.bin"
            address: 0xc000
          - file: "/roms/901465-21.bin"
            address: 0xd000
          - file: "/roms/901474-03.bin"
            address: 0xe000
          - file: "/roms/901465-22.bin"
            address: 0xf000
  - name: "Basic 4.0 (80 Col 50 Hz)"
    setup:
      - action: "load"
        files:
          - file: "/roms/901447-10.bin"
            address: 0x8800
          - file: "/roms/901465-19.bin"
            address: 0xb000
          - file: "/roms/901465-20.bin"
            address: 0xc000
          - file: "/roms/901465-21.bin"
            address: 0xd000
          - file: "/roms/901474-04.bin"
            address: 0xe000
          - file: "/roms/901465-22.bin"
            address: 0xf000
